### ISSUE TITLE
About the Pom.xml

### ISSUE THREAD

**Issue by lijinchi** [SAP-samples/cloud-espm-cloud-native#15]
Although I am a BTP trial account, but the POM of all modules after cloning the project does not recognize the parent module:Non-resolvable parent POM. Is this caused by the BAS editor? 
Maybe I can build it just in my IDEA locally，then cf push？
Thanks for you time if you can solve this problem.

**Comment by shankarigr** [comment]
Can you please checkout the latest code and try building again?

**Comment by lijinchi** [comment]
All right its compiling  normally!

**Comment by shankarigr** [comment]
ok thanks. Closing the issue.
