### ISSUE TITLE
A issue when cf push

### ISSUE THREAD

**Issue by lijinchi** [SAP-samples/cloud-espm-cloud-native#16]
Hi.
because i want run in my trial acount,so i keep the common and customer-service module.
then i change the manifest.yml、mta.yml and properites to use HANAdb, finally it crashed.
**Field customerRepository in com.sap.refapps.espm.service.CustomerServiceImpl required a bean named 'entityManagerFactory' that could not be found.**

this is manifest.yml
<img width="394" alt="yml" src="https://user-images.githubusercontent.com/26862721/166238272-1382a9d8-231b-4719-886a-4b144bc27d20.png">

properites
![image](https://user-images.githubusercontent.com/26862721/166238430-dc29c129-29f3-4408-8bb2-8d45446e0aa7.png)

and the recent logs
![image](https://user-images.githubusercontent.com/26862721/166238613-4164ff62-69ac-4290-8035-81450547842b.png)
![image](https://user-images.githubusercontent.com/26862721/166238734-36bbe740-d9cf-47e7-9719-b00c2e0f093c.png)
![image](https://user-images.githubusercontent.com/26862721/166238775-b3cb8253-631a-480a-9a34-24f27c6a24b3.png)

**Comment by lijinchi** [comment]
the configuration  about hanacloud have certificates but datasource didnt config this, for example hdi_user,how can I use it?

**Comment by shankarigr** [comment]
@lijinchi , are you running Customer service locally or you deploying it to CF? 
Properties file is not required while deploying to CF. It is only required when you run application locally.
can you please elaborate the changes you have made?
