### ISSUE TITLE
Need update 

### ISSUE THREAD

**Issue by lijinchi** [SAP-samples/cloud-espm-cloud-native#20]
<img width="687" alt="0B8D9E21-5710-4D0C-BA9D-A9A8FBB047AA" src="https://user-images.githubusercontent.com/26862721/170191420-1149f352-e53a-43c4-a5b9-69dccf3af098.png">
Some libraries will be removed after Dec 2022

**Comment by biswaranjanray** [comment]
Hi @lijinchi,

Thanks for sharing your observation. Spring cloud connectors are migrated to java-cfenv in the app and that essentially removed all the warnings related to spring auto reconfiguration and cloud connectors.

Best Regards,
Biswa Ranjan Ray
