### ISSUE TITLE
Created Sales Order is not listed in Retailer View

### ISSUE THREAD

**Issue by i047823** [SAP-samples/cloud-espm-cloud-native#21]
Once the sales order is created in webshop view  the sales order details is not shown in retailer view.

Steps to reproduce:

Launch URL for Webshop application 
https://espmauto-dev-espm-gateway.cfapps.eu10.hana.ondemand.com/webapp/webshop/index.html
Login with existing customer "paul.burke@itelo.info".
Add some item to cart and checkout to create sales order.
It says sales order created.

Now click on the sales order icon next to the cart icon. 
Expected : It should display the sales order information created by the webshop user.
Actual : The sales order information is not shown.

Launch url for retailer application :
https://espmauto-dev-espm-gateway.cfapps.eu10.hana.ondemand.com/webapp/retailer/index.html

Click on sales order view
Expected : created sales order should be displayed with status.
Actual : sales order info not shown.

Attached the screenshots.
![espm error1](https://user-images.githubusercontent.com/106370221/170650878-7ea2fbed-bb6f-4386-a70a-35f40e920606.png)
![espm error2](https://user-images.githubusercontent.com/106370221/170650884-7a90c2c3-0e8d-46a5-b9aa-eef9c8aaaa2b.png)

**Comment by navinkrishnan** [comment]
Will be tracked separately
