### ISSUE TITLE
Product with quantity zero is getting added to the cart

### ISSUE THREAD

**Issue by i047823** [SAP-samples/cloud-espm-cloud-native#22]
While adding the product items to the cart, when we fill the quantity as 0 and click on the "add to cart" icon. the Items is added to the cart.

Steps to reproduce:
Launch ESPM Webshop application 
https://espmauto-dev-espm-gateway.cfapps.eu10.hana.ondemand.com/webapp/webshop/index.html

login with existing customer "paul.burke@itelo.info"
Edit the number of quantity to 0 for any item
Click add to cart icon
Result : the item gets added to cart.
Expected : the item should not be added and should throw a error message with minimum quantity to add to cart.

Attached the screenshot
![Uploading esmp_error3.GIF…]()

**Comment by navinkrishnan** [comment]
Will be tracked separately
