### ISSUE TITLE
App has not started, app crashed while deploying

### ISSUE THREAD

**Issue by SreekanthGudisi** [SAP-samples/cloud-espm-cloud-native#4]
Hi
App getting crashed while deploying the app. For ex: Im tyring to deploy the app `cf push i302342-espm-product-svc`.

![image](https://user-images.githubusercontent.com/23524697/71525435-b2cc7b80-28f7-11ea-8424-fee9d3d7e458.png)

Attached the log.

[i302342-espm-product-svc-2019-12-27 16_47_02.431+0000.txt](https://github.com/SAP-samples/cloud-espm-cloud-native/files/4005809/i302342-espm-product-svc-2019-12-27.16_47_02.431%2B0000.txt)

Any help why the app is getting crashed.

**Comment by mahaluckshmi** [comment]
Hi, Kindly use the same hana service name in all config files. 
Example: https://github.com/SAP-samples/cloud-espm-cloud-native/blob/master/product-service/src/main/java/com/sap/refapps/espm/config/HanaDataSourceConfig.java#L22 , replace "espm-hana-db" with the name of the service you created.
