### ISSUE TITLE
Xsuaa oAuth Issue - Approuter authentication fails even though roles are present

### ISSUE THREAD

**Issue by balajip36** [SAP-samples/cloud-espm-cloud-native#55]
Dear Team,
We are currently trying out the ESPM Cloud Native as a reference app . 
After deployment of the ESPM Cloud Native app to cloud foundry, 
I sent a request to the endpoint **/product.svc/api/v1/products/** 
This is done after assigning the scope **"$XSAPPNAME.Update"** to the product endpoint both at app router and Spring security configuration at the ant matchers. 
The user doing the request is not assigned the retailer role. So he has no scope for this.
(the Jwt snapshot is attached). 
Irrespective of the scopes assigned. The approuter always gives 401 unauthorized. 

When tried out directly with the product service uri, the products are shown with 200 response. 
There is a problem with the authority mentioned., as I could see the security configuration is not applied by the service. 
Kindly help us on this.

<img width="710" alt="Screenshot 2023-12-22 at 18 52 25" src="https://github.com/SAP-samples/cloud-espm-cloud-native/assets/139250938/a0419231-dd5e-446a-b605-f0f2cfff7ef4">

<img width="608" alt="Screenshot 2023-12-22 at 18 56 54" src="https://github.com/SAP-samples/cloud-espm-cloud-native/assets/139250938/f146f58a-4145-4058-8e12-2e6443be16a7">

<img width="1017" alt="Screenshot 2023-12-22 at 18 58 42" src="https://github.com/SAP-samples/cloud-espm-cloud-native/assets/139250938/40e419b0-f34a-435c-9d4f-29206ab06303">

Best Regards,
Balaji Vengatesh M

**Comment by shankarigr** [comment]
Hello Balaji,

Thanks for reaching out to us.
Inspite of assigning the retailer role are you getting 401 unauthorized?

Regards,
Shankari G R

**Comment by balajip36** [comment]
Hi Shankari,

Yes. That is correct.

Best Regards,
Balaji Vengatesh M

**Comment by singhabhi1999** [comment]
Hello Balaji,

Since you can access the  endpoint /product.svc/api/v1/products/  directly through http client, there is issue with the token forwarded by the approuter to backend service. Can you please send us and compare the token forwarded by approuter and the token you generated using http client tool.

**Comment by balajip36** [comment]
Hi Abhinav,

The call never hits the service when approuter is used. It always generates a 401 error even though the scopes are present and is passed through the jwt token. 

Br,
Balaji Vengatesh M

**Comment by singhabhi1999** [comment]
Hi Balaji,

Then there is some issue with the routing configuration in the approuter. Let us reproduce the issue and will get back to you as soon as possible.

Regards,
Abhinav

**Comment by singhabhi1999** [comment]
Hi Balaji,

Can you please send us your approuter logs and xs-app.json file

**Comment by balajip36** [comment]
Hi Abhinav,

Please find the xs-app.json config
[xs-app.json](https://github.com/SAP-samples/cloud-espm-cloud-native/files/13809337/xs-app.json)

Br,
Balaji Vengatesh M

**Comment by VanitaDhanagar** [comment]
Hi Balaji ,

With xsapp.json file provided by you 
1. Are you applying scope to product service?
if yes ,reason?

Regards,
Vanita

**Comment by balajip36** [comment]
Hi Vanita,

We are currently working on to test a project, where we only require a plain service with XSUAA to run without other dependencies. 
Product service fits the bill thats why.
Kindly look into the pictures attached, As we have changed the security config accordingly. 

Br,
Balaji Vengatesh M

**Comment by VanitaDhanagar** [comment]
Hi Balaji ,

Please find my xs-app.json file below
[xs-app.json](https://github.com/SAP-samples/cloud-espm-cloud-native/files/14008091/xs-app.json)

The same request is handeled in other services ,please look into it ,like retailer page.

Regards,
vanita

**Comment by balajip36** [comment]
Hi Vanita,

Please find my xs-app.json too. There are not much changes,  Im running only two services and Im not concerned about the UI for now.  Can you check if this is working for you?

{
  "welcomeFile": "/webapp/webshop/index.html",
  "authenticationMethod": "route",
  "logout": {
    "logoutEndpoint": "/do/logout"
  },
  "routes": [
	{
	  "source": "^/product.svc/api/v1/products/(.*)",
	  "destination": "product-service",
	  "csrfProtection": false,
	  "scope": "$XSAPPNAME.Update",
	  "httpMethods": ["GET"]
	},
	
	{
	  "source": "^/customer.svc/api/(.*)",
	  "destination": "customer-service",
	  "csrfProtection": false,
	  "httpMethods": ["GET","POST","PUT","DELETE"]
	},
    {
      "source": "^/webapp/retailer/(.*)",
      "localDir": ".",
      "replace": {
        "pathSuffixes": [
          "index.html"
        ]
	  },
	  "scope": "$XSAPPNAME.Update",
	  "authenticationType": "xsuaa"
    },
    {
      "source": "^/webapp/webshop/(.*)",
      "localDir": ".",
      "replace": {
        "pathSuffixes": [
          "index.html"
        ]
      },
	"authenticationType": "xsuaa"
    }
    ]
}



Best Regards,
Balaji Vengatesh Murugesan

**Comment by VanitaDhanagar** [comment]
Hi Balaji ,

I also have two services added in shared file ,Please check .

Regards,
Vanita

**Comment by balajip36** [comment]
Hi Vanita,
It doesn't work. The same issue is present.
 Please let me know what is the point in deploying authorizations for services that you donot call or use?

Br,
Balaji Vengatesh Murugesan

**Comment by shankarigr** [comment]
Hi Balaji,

We understood your requirement is to have a simple application with authorization. That we had addressed. 
The above solution works perfectly for us.

We are not able to understand your requirements clearly. If the above solution doesnt work for you, we will be able to look more into it only if you can provide us the error logs, your Springboot version, etc.

If you are looking for a custom implementation with xsuaa, please do create a Customer ticket.

Regards,
Shankari G R

**Comment by balajip36** [comment]
Hi Shankari

Im not looking for a custom implementation. 
But rather a simple implementation of Standalone approuter on top of a Spring Boot app. 
The problem is the authorization fails for HttpMethod GET
I have shared with you my jwt tokens, Approuter error logs and response from postman. 

The current Spring Boot version used is 2.7.7

I have attached the video showing you exactly the problem 
This shows the logs and workings completly
If you need more, kindly let me know

https://projektraum36-my.sharepoint.com/:v:/g/personal/balaji_murugesan_p36_io/Efz512qlp99Ip267Y8CHpXwBwCLI8wK5phu6jUQcbK-I9g?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&email=shankari.gr%40sap.com&e=LDHe9N

https://projektraum36-my.sharepoint.com/:v:/g/personal/balaji_murugesan_p36_io/ESSbiaINEZtPn_24moz-qg0ByR1QtCRIrMkQR7CmovlZvg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&email=shankari.gr%40sap.com&e=ajT7h8

Br,
Balaji Vengatesh Murugesan

**Comment by balajip36** [comment]
Hi Shankari

Thanks for your help.  i think the app works without roles for the given service but not with a role. 

Br,
Balaji Vengatesh M
