### ISSUE TITLE
Sale order creation cancelled - 500 internal server error, while creating sales order

### ISSUE THREAD

**Issue by manjunathgudisi** [SAP-samples/cloud-espm-cloud-native#6]
Hi

I have successfully deployed all the apps using cf deploy command. Also created all the necesseary service instances like espm-destinations espm-em, espm-hana-db..etc.

Getting "Sale order creation cancelled " message when I try to create a sale order in webshop app. 

Here is the network log (from Inspect element)

{"timestamp":"2020-04-15T07:07:33.594+0000","status":500,"error":"Internal Server Error","message":"target (topic/queue) forbidden (220056) [condition = amqp:internal-error]","path":"/sale.svc/api/v1/salesOrders"}

Here is the `cf logs espm-sales-svc`

<img width="1317" alt="Screen Shot 2020-04-15 at 12 46 03 PM" src="https://user-images.githubusercontent.com/6059076/79309315-b8d28080-7f17-11ea-928c-a39fa6232f24.png">

Seems to be this is an issue enterprise messaging. Could you please help me where Im doing wrong.

<img width="1367" alt="Screen Shot 2020-04-15 at 12 51 22 PM" src="https://user-images.githubusercontent.com/6059076/79309392-d6074f00-7f17-11ea-8333-cef2bf258b33.png">

Thank you, Manju

**Comment by indusankar89** [comment]
Hi Manju,

Have you edited the Queue_name in [manifest.yml file](https://github.com/SAP-samples/cloud-espm-cloud-native/blob/master/manifest.yml#L32) to the one that u have created. 

Regards,
Indu

**Comment by manjunathgudisi** [comment]
Hi @indusankar89 
yes, I have done it already and it is like this in manifest.yml file
`QUEUE_NAME: "demo/espm/messages/salesorderqueue"`

**Comment by manjunathgudisi** [comment]
Thank you @indusankar89 for your call. I have fixed the issue as you mentioned. It was an issue with QUEUE_NAME in mta.yml file. Thank you once again.
