### ISSUE TITLE
Unable to see Stock information  

### ISSUE THREAD

**Issue by manjunathgudisi** [SAP-samples/cloud-espm-cloud-native#7]
<img width="1153" alt="Screen Shot 2020-04-15 at 7 42 50 PM" src="https://user-images.githubusercontent.com/6059076/79347646-89406a00-7f51-11ea-9539-58d2be129c2f.png">

When I tried to open "Stock availability" app, I get the messages like below

`The target you tried to get "StockInformation" does not exist! - EventProvider sap.m.routing.Targets `

Could you please help me.

Thank you, Manju

**Comment by mahaluckshmi** [comment]
Hi Manju,

It hasn't been implemented yet. We will try to add proper message or remove it.

Thank you.
